#!/bin/bash

echo "make sure metadata.yaml is set for standalone"
echo "i.e., comment out the subordinate and requires sections"
exit 0

juju bootstrap

juju deploy --repository ~/charms local:juju juju-bare
juju deploy --repository ~/charms --config juju-repo.yaml local:juju juju-repo
juju deploy --repository ~/charms --config juju-repo-precached.yaml local:juju juju-repo-precached

