#!/bin/bash

set -eu

install_juju() {
  juju-log "installing/updating juju client components"
  [ -f lib/juju-client.sh ] && . lib/juju-client.sh && install_juju_client ubuntu /home/ubuntu

  juju-log "done installing juju"
}
install_juju

